### ISSUE TITLE
How to study ppl and bayes inference

### ISSUE THREAD

**Issue by hitdshu** [yiyuezhuo/Y-PPL#1]
Hi yiyuezhuo,

Recently I feel interesed in probabilistic programming and bayesian inference. 

Can you tell me where to study ppl and write a similar system like you? Thanks.

Best,
Deshun

**Comment by yiyuezhuo** [comment]
Some materials:

Probabilistic Programming and Bayesian Methods for Hackers
https://nbviewer.jupyter.org/github/CamDavidsonPilon/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers/blob/master/Chapter1_Introduction/Ch1_Introduction_PyMC3.ipynb

Stan User guide
https://mc-stan.org/docs/2_22/stan-users-guide/index.html
User guide and many researchers also recommended the textbook "Bayesian Data Analysis and Statistical Rethinking: A Bayesian Course with Examples in R and Stan" but I haven't read it.

**Comment by hitdshu** [comment]
> Some materials:
> 
> Probabilistic Programming and Bayesian Methods for Hackers
> https://nbviewer.jupyter.org/github/CamDavidsonPilon/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers/blob/master/Chapter1_Introduction/Ch1_Introduction_PyMC3.ipynb
> 
> Stan User guide
> https://mc-stan.org/docs/2_22/stan-users-guide/index.html
> User guide and many researchers also recommended the textbook "Bayesian Data Analysis and Statistical Rethinking: A Bayesian Course with Examples in R and Stan" but I haven't read it.

Thanks for your kind reply. I'm studying this online course https://kayhan.dbmi.pitt.edu/node/38 and hope it suffices. I'll read your recommended materials once I understand the basics. 

Best,
Deshun
